### ISSUE TITLE
[Agent] container has runAsNonRoot and image has non-numeric user

### ISSUE THREAD

**Issue by gmtstephane** [gmtstephane/kpture#1]
In some cases, the ephemeral container fail to start on non privilged pods with the following Error :

```yaml
  ephemeralContainerStatuses:
  - image: ghcr.io/gmtstephane/kpture:latest
    imageID: ""
    lastState: {}
    name: kpture-d2108ca4-829d-4f13-9603-cf7ee06c8877
    ready: false
    restartCount: 0
    state:
      waiting:
        message: 'container has runAsNonRoot and image has non-numeric user (kpture),
          cannot verify user is non-root (pod: "smf-smf-n4-redis-master-0_default(6d8b6b4a-8374-4700-9c15-66b5aba46911)",
          container: kpture-d2108ca4-829d-4f13-9603-cf7ee06c8877)'
        reason: CreateContainerConfigError
```
